/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:1b3ff8e2-8fbe-4415-892f-9d6f7612107b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_gaMjf0acS",
    "aws_user_pools_web_client_id": "47bcgvtajmolakvkknrgg0lbtg",
    "oauth": {}
};


export default awsmobile;
